### ISSUE TITLE
BUG: Exporting a character's animation with "Zero Character" doesn't zero out rotations

### ISSUE THREAD

**Issue by TheSleepyDino** [V1Interactive/FreeformTools#42]
When I have "Zero Character" as an export setting, the character has zero'd out positions, but not zero'd out rotations at start frame. It would be ideal if both positions and rotations are zero'd out so character starts from origin.

**Comment by zahmbie** [comment]
I added a new property for zero-ing out rotation.  This way you can choose if you want one or the other, or both by adding both properties to the export.
