### ISSUE TITLE
BUG: Aim overdriver doesn't bake keys to selected (driver) locator

### ISSUE THREAD

**Issue by TheSleepyDino** [V1Interactive/FreeformTools#43]
Aim overdriver doesn't carry over the animation to the locator that's driving the rotations.
1. Create a locator
2. Select locator, shift select control (locator is driver, control is drivee)
3. Click on aim overdriver button.

Overdriver is created but no animation is baked onto the locator to maintain the pre-existing animation from the control. Tried with both Bake Settings: "Time Range" and "Timeline Keys".

**Comment by TheSleepyDino** [comment]
I just checked and it does work with "Bake Component" checked. However, it's a little confusing that it's not the default behavior since the other Overdrivers bake component. Is it possible to flip flop this and have a manual checkbox where it disables bake? This is mostly so I can keep my "Delete Rig Component" (the red X tools button) button.

**Comment by zahmbie** [comment]
Added a setting to not bake overdrivers that the AIM and all other Overdrivers respect.  Overdrivers already save this preference into the rigging file, so any saved overdriver that was built to not bake will continue to not bake when it's loaded from file.
