### ISSUE TITLE
Request: Bake settings "Time Range" changed to "Active Time Range"

### ISSUE THREAD

**Issue by TheSleepyDino** [V1Interactive/FreeformTools#45]
The way Maya's default bake simulation works is if you select "Time Range" it means the active time range that's framed on the time slider. 

In the example below: Frames 20-60 would bake.

![image](https://user-images.githubusercontent.com/74645961/121576447-3c351800-c9dd-11eb-8d9a-1c2744b2ca1b.png)

Currently, in Helix Tools the "Time Range" bake settings are set to the entire set time range (i.e. frames 0-60 instead of 20-60). It would be great if the bake settings were for active time range/what's actively framed on the time slider.

All the other behavior of maintaining outside keys of the active frame range during a bake should still be respected as well as baking the timeline keys when swapping rigging JSONs.

**Comment by zahmbie** [comment]
Changed to use the min/max timeline values instead of the outer range values.
