### ISSUE TITLE
Request: World Space Overdriver to apply to end targets when using translate spine/tail

### ISSUE THREAD

**Issue by TheSleepyDino** [V1Interactive/FreeformTools#46]
The world space overdriver is great for controls, but unfortunately, they don't work with locator target end points when using translate_spine (head) and translate_tail (end of tail). Maybe a general tool that converts to world space (translate, rotate, or both) instead...?

**Comment by zahmbie** [comment]
Can you send me the error you get when you try to apply the Overdriver to the locator?  It works on my end, though for overdrivers the tools just copy the control shape to use for the overdriver control, and locator's can't receive a material, so it ends up looking the same.  But the UI should update to show you the last control is driven by an overdriver and values should all be put into world space

**Comment by TheSleepyDino** [comment]
Oh! I had no idea it worked on locators. I just tried it out and verified it works fine.
