### ISSUE TITLE
Request: Bake the driver instead of control while space switching

### ISSUE THREAD

**Issue by TheSleepyDino** [V1Interactive/FreeformTools#57]
A toggle-able option(?) where you can bake the driver instead the control when you space switch so you can edit the animation from the driver's space instead.

**Comment by zahmbie** [comment]
Added this toggle to the settings menu, checkbox "Bake Driver Object" will bake animation onto the driver control objects instead of the overdriver control when you make overdrivers.  Since it broadly applies to overdrivers lets chat about how best to represent it as buttons in the toolbar.
